"""Official indicator tree structure for the VDT backend.

This file defines the shape of the tree only: ids, labels, types, units and
children. Actual numbers come from ``data_source.py`` and formulas from
``formulas.py``.
"""

try:
    from .models import IndicatorStructure
except ImportError:
    from models import IndicatorStructure


# The tree is laid out in business order so the next editor can find a node fast.
INDICATOR_STRUCTURES = [
    IndicatorStructure(**{
        "id": "ebitda",
        "label": "EBITDA",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "ebitda_formula",
        "children": [
            "net_revenue",
            "operating_costs",
        ],
    }),
    IndicatorStructure(**{
        "id": "net_revenue",
        "label": "Receita Líquida",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "net_revenue_formula",
        "children": [
            "gross_revenue",
            "smelters",
        ],
    }),
    IndicatorStructure(**{
        "id": "smelters",
        "label": "Smelters",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "treatment_dmt",
            "refining_payable",
            "penalties_mgo",
        ],
    }),
    IndicatorStructure(**{
        "id": "treatment_dmt",
        "label": "Treatment (dmt)",
        "type": "input",
        "unit": "kUSD",
        "group": "Smelters",
    }),
    IndicatorStructure(**{
        "id": "refining_payable",
        "label": "Refining (Payable)",
        "type": "input",
        "unit": "kUSD",
        "group": "Smelters",
    }),
    IndicatorStructure(**{
        "id": "penalties_mgo",
        "label": "Penalties (MgO)",
        "type": "input",
        "unit": "kUSD",
        "group": "Smelters",
    }),
    IndicatorStructure(**{
        "id": "gross_revenue",
        "label": "Receita Bruta",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "gross_revenue_formula",
        "children": [
            "copper_revenue",
            "gold_revenue",
        ],
    }),
    IndicatorStructure(**{
        "id": "copper_revenue",
        "label": "Receita do Cu",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "copper_revenue_formula",
        "children": [
            "contained_copper",
            "cu_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "contained_copper",
        "label": "Cobre Contido",
        "type": "formula",
        "unit": "t",
        "formulaId": "contained_copper_formula",
        "children": [
            "wet_feed_mass",
            "head_grade",
            "cu_recovery",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass",
        "label": "Massa de Alim. Via Úmida",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_formula",
        "children": [
            "wet_route_productivity",
            "wet_route_efficiency",
            "wet_route_calendar_hours",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_route_efficiency",
        "label": "Eficiência da Via Úmida",
        "type": "formula",
        "unit": "%",
        "formulaId": "wet_route_efficiency_formula",
        "children": [
            "df_wet_route",
            "ut_wet_route",
        ],
    }),
    IndicatorStructure(**{
        "id": "df_wet_route",
        "label": "DF Via Úmida",
        "type": "input",
        "unit": "%",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "ut_wet_route",
        "label": "UT Via Úmida",
        "type": "formula",
        "unit": "%",
        "formulaId": "ut_wet_route_formula",
        "children": [
            "hmp",
            "hmnp",
            "stopped_hours",
        ],
    }),
    IndicatorStructure(**{
        "id": "hmp",
        "label": "HMP",
        "type": "input",
        "unit": "h",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "hmnp",
        "label": "HMNP",
        "type": "input",
        "unit": "h",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "stopped_hours",
        "label": "Horas Paradas",
        "type": "input",
        "unit": "h",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "wet_route_calendar_hours",
        "label": "Horas Calendário",
        "type": "input",
        "unit": "h",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "wet_route_productivity",
        "label": "Produtividade Via Úmida",
        "type": "input",
        "unit": "t/h",
        "group": "Via Úmida",
    }),
    IndicatorStructure(**{
        "id": "head_grade",
        "label": "Head Grade",
        "type": "input",
        "unit": "% Cu",
        "group": "Receita Cu",
    }),
    IndicatorStructure(**{
        "id": "cu_recovery",
        "label": "Rec. Cu",
        "type": "input",
        "unit": "%",
        "group": "Receita Cu",
    }),
    IndicatorStructure(**{
        "id": "cu_price",
        "label": "Preço do Cu",
        "type": "input",
        "unit": "USD/t",
        "group": "Receita Cu",
    }),
    IndicatorStructure(**{
        "id": "gold_revenue",
        "label": "Receita do Ouro",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "gold_revenue_formula",
        "children": [
            "contained_gold_concentrate",
            "gold_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "contained_gold_concentrate",
        "label": "Ouro Contido no Concentrado",
        "type": "formula",
        "unit": "oz",
        "formulaId": "contained_gold_formula",
        "children": [
            "concentrate_mass",
            "gold_concentrate_grade",
        ],
    }),
    IndicatorStructure(**{
        "id": "concentrate_mass",
        "label": "Massa de Concentrado Cu",
        "type": "formula",
        "unit": "t",
        "formulaId": "concentrate_mass_formula",
        "children": [
            "contained_copper_reference",
            "cu_concentrate_grade",
        ],
    }),
    IndicatorStructure(**{
        "id": "contained_copper_reference",
        "label": "Cobre Contido (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "contained_copper_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "cu_concentrate_grade",
        "label": "Teor de Conc. do Cu",
        "type": "input",
        "unit": "% Cu",
        "group": "Receita Cu",
    }),
    IndicatorStructure(**{
        "id": "gold_concentrate_grade",
        "label": "Teor de Conc. do Ouro",
        "type": "input",
        "unit": "oz/t",
        "group": "Receita Ouro",
    }),
    IndicatorStructure(**{
        "id": "gold_price",
        "label": "Preço do Ouro",
        "type": "input",
        "unit": "USD/oz",
        "group": "Receita Ouro",
    }),
    IndicatorStructure(**{
        "id": "operating_costs",
        "label": "Custos Operacionais",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "operating_costs_formula",
        "children": [
            "support_costs",
            "production_costs",
        ],
    }),
    IndicatorStructure(**{
        "id": "support_costs",
        "label": "Custos de Suporte",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "ga_site",
            "bh_office",
        ],
    }),
    IndicatorStructure(**{
        "id": "ga_site",
        "label": "G&A Site",
        "type": "input",
        "unit": "kUSD",
        "group": "Suporte",
    }),
    IndicatorStructure(**{
        "id": "bh_office",
        "label": "BH Office",
        "type": "input",
        "unit": "kUSD",
        "group": "Suporte",
    }),
    IndicatorStructure(**{
        "id": "production_costs",
        "label": "Custos de Produção",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "production_costs_formula",
        "children": [
            "mine_costs",
            "plant_costs",
            "logistics_costs",
        ],
    }),
    IndicatorStructure(**{
        "id": "mine_costs",
        "label": "Custos da Mina",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "drill_blasting",
            "hauling",
            "loading",
            "mine_labour",
            "ga_services",
            "fuel",
            "mine_support",
        ],
    }),
    IndicatorStructure(**{
        "id": "drill_blasting",
        "label": "Drill & Blasting",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "hauling",
        "label": "Hauling",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "loading",
        "label": "Loading",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "mine_labour",
        "label": "Labour",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "ga_services",
        "label": "G&A Services",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "fuel",
        "label": "Fuel",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "mine_support",
        "label": "Support",
        "type": "input",
        "unit": "kUSD",
        "group": "Mina",
    }),
    IndicatorStructure(**{
        "id": "plant_costs",
        "label": "Custos da Planta",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "consumables",
            "power",
            "materials",
            "services",
            "labour_ga",
            "water",
            "laboratory",
            "lube_fuel",
            "tsf",
        ],
    }),
    IndicatorStructure(**{
        "id": "consumables",
        "label": "Consumables",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "mill_balls",
            "reagents",
        ],
    }),
    IndicatorStructure(**{
        "id": "mill_balls",
        "label": "Mill Balls",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "ball_aço_4_cost",
            "ball_aço_3_cost",
            "ceramic_ball_hig_1_cost",
            "ceramic_ball_hig_2_cost",
        ],
    }),
    IndicatorStructure(**{
        "id": "ball_aço_4_cost",
        "label": "Custo Bola Aço 4\"",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "ball_aço_4_formula",
        "children": [
            "ball_aço_4_quantity",
            "ball_aço_4_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "ball_aço_4_quantity",
        "label": "Quantidade Bola Aço 4\"",
        "type": "formula",
        "unit": "t",
        "formulaId": "ball_aço_4_qty_formula",
        "children": [
            "ball_aço_4_consumption",
            "wet_feed_mass_ref_ball_aço_4",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_ball_aço_4",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "ball_aço_4_consumption",
        "label": "Consumo Específico Bola Aço 4\"",
        "type": "input",
        "unit": "kg/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ball_aço_4_price",
        "label": "Preço Bola Aço 4\"",
        "type": "input",
        "unit": "USD/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ball_aço_3_cost",
        "label": "Custo Bola Aço 3\"",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "ball_aço_3_formula",
        "children": [
            "ball_aço_3_quantity",
            "ball_aço_3_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "ball_aço_3_quantity",
        "label": "Quantidade Bola Aço 3\"",
        "type": "formula",
        "unit": "t",
        "formulaId": "ball_aço_3_qty_formula",
        "children": [
            "ball_aço_3_consumption",
            "wet_feed_mass_ref_ball_aço_3",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_ball_aço_3",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "ball_aço_3_consumption",
        "label": "Consumo Específico Bola Aço 3\"",
        "type": "input",
        "unit": "kg/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ball_aço_3_price",
        "label": "Preço Bola Aço 3\"",
        "type": "input",
        "unit": "USD/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_1_cost",
        "label": "Custo Bola Cerâmica Hig 1 (2 a 3 mm)",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "ceramic_ball_hig_1_formula",
        "children": [
            "ceramic_ball_hig_1_quantity",
            "ceramic_ball_hig_1_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_1_quantity",
        "label": "Quantidade Cerâmica Hig 1",
        "type": "formula",
        "unit": "t",
        "formulaId": "ceramic_ball_hig_1_qty_formula",
        "children": [
            "ceramic_ball_hig_1_consumption",
            "wet_feed_mass_ref_ceramic_ball_hig_1",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_ceramic_ball_hig_1",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_1_consumption",
        "label": "Consumo Específico Cerâmica Hig 1",
        "type": "input",
        "unit": "kg/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_1_price",
        "label": "Preço Cerâmica Hig 1",
        "type": "input",
        "unit": "USD/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_2_cost",
        "label": "Custo Bola Cerâmica Hig 2 (4 a 5 mm)",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "ceramic_ball_hig_2_formula",
        "children": [
            "ceramic_ball_hig_2_quantity",
            "ceramic_ball_hig_2_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_2_quantity",
        "label": "Quantidade Cerâmica Hig 2",
        "type": "formula",
        "unit": "t",
        "formulaId": "ceramic_ball_hig_2_qty_formula",
        "children": [
            "ceramic_ball_hig_2_consumption",
            "wet_feed_mass_ref_ceramic_ball_hig_2",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_ceramic_ball_hig_2",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_2_consumption",
        "label": "Consumo Específico Cerâmica Hig 2",
        "type": "input",
        "unit": "kg/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "ceramic_ball_hig_2_price",
        "label": "Preço Cerâmica Hig 2",
        "type": "input",
        "unit": "USD/t",
        "group": "Mill Balls",
    }),
    IndicatorStructure(**{
        "id": "reagents",
        "label": "Reagents",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "flocculant_cost",
            "frother_cost",
            "collector_1_cost",
            "collector_2_cost",
            "lime_cost",
            "depressor_cost",
            "activator_cost",
        ],
    }),
    IndicatorStructure(**{
        "id": "flocculant_cost",
        "label": "Custo de Floculante",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "flocculant_formula",
        "children": [
            "flocculant_quantity",
            "flocculant_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "flocculant_quantity",
        "label": "Quantidade Floculante",
        "type": "formula",
        "unit": "t",
        "formulaId": "flocculant_qty_formula",
        "children": [
            "flocculant_consumption",
            "wet_feed_mass_ref_flocculant",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_flocculant",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "flocculant_consumption",
        "label": "Consumo Específico Floculante",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "flocculant_price",
        "label": "Preço Floculante",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "frother_cost",
        "label": "Custo de Espumante",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "frother_formula",
        "children": [
            "frother_quantity",
            "frother_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "frother_quantity",
        "label": "Quantidade Espumante",
        "type": "formula",
        "unit": "t",
        "formulaId": "frother_qty_formula",
        "children": [
            "frother_consumption",
            "wet_feed_mass_ref_frother",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_frother",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "frother_consumption",
        "label": "Consumo Específico Espumante",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "frother_price",
        "label": "Preço Espumante",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "collector_1_cost",
        "label": "Custo de Coletor 1",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "collector_1_formula",
        "children": [
            "collector_1_quantity",
            "collector_1_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "collector_1_quantity",
        "label": "Quantidade Coletor 1",
        "type": "formula",
        "unit": "t",
        "formulaId": "collector_1_qty_formula",
        "children": [
            "collector_1_consumption",
            "wet_feed_mass_ref_collector_1",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_collector_1",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "collector_1_consumption",
        "label": "Consumo Específico Coletor 1",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "collector_1_price",
        "label": "Preço Coletor 1",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "collector_2_cost",
        "label": "Custo de Coletor 2",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "collector_2_formula",
        "children": [
            "collector_2_quantity",
            "collector_2_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "collector_2_quantity",
        "label": "Quantidade Coletor 2",
        "type": "formula",
        "unit": "t",
        "formulaId": "collector_2_qty_formula",
        "children": [
            "collector_2_consumption",
            "wet_feed_mass_ref_collector_2",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_collector_2",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "collector_2_consumption",
        "label": "Consumo Específico Coletor 2",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "collector_2_price",
        "label": "Preço Coletor 2",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "lime_cost",
        "label": "Custo de Cal",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "lime_formula",
        "children": [
            "lime_quantity",
            "lime_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "lime_quantity",
        "label": "Quantidade Cal",
        "type": "formula",
        "unit": "t",
        "formulaId": "lime_qty_formula",
        "children": [
            "lime_consumption",
            "wet_feed_mass_ref_lime",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_lime",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "lime_consumption",
        "label": "Consumo Específico Cal",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "lime_price",
        "label": "Preço Cal",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "depressor_cost",
        "label": "Custo de Depressor",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "depressor_formula",
        "children": [
            "depressor_quantity",
            "depressor_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "depressor_quantity",
        "label": "Quantidade Depressor",
        "type": "formula",
        "unit": "t",
        "formulaId": "depressor_qty_formula",
        "children": [
            "depressor_consumption",
            "wet_feed_mass_ref_depressor",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_depressor",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "depressor_consumption",
        "label": "Consumo Específico Depressor",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "depressor_price",
        "label": "Preço Depressor",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "activator_cost",
        "label": "Custo de Ativador",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "activator_formula",
        "children": [
            "activator_quantity",
            "activator_price",
        ],
    }),
    IndicatorStructure(**{
        "id": "activator_quantity",
        "label": "Quantidade Ativador",
        "type": "formula",
        "unit": "t",
        "formulaId": "activator_qty_formula",
        "children": [
            "activator_consumption",
            "wet_feed_mass_ref_activator",
        ],
    }),
    IndicatorStructure(**{
        "id": "wet_feed_mass_ref_activator",
        "label": "Massa de Alim. Via Úmida (ref.)",
        "type": "formula",
        "unit": "t",
        "formulaId": "wet_feed_mass_reference_formula",
    }),
    IndicatorStructure(**{
        "id": "activator_consumption",
        "label": "Consumo Específico Ativador",
        "type": "input",
        "unit": "kg/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "activator_price",
        "label": "Preço Ativador",
        "type": "input",
        "unit": "USD/t",
        "group": "Reagentes",
    }),
    IndicatorStructure(**{
        "id": "power",
        "label": "Power",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "materials",
        "label": "Materials",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "services",
        "label": "Services",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "labour_ga",
        "label": "Labour & G&A",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "water",
        "label": "Water",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "laboratory",
        "label": "Laboratory",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "lube_fuel",
        "label": "Lube & Fuel",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "tsf",
        "label": "TSF",
        "type": "input",
        "unit": "kUSD",
        "group": "Planta",
    }),
    IndicatorStructure(**{
        "id": "logistics_costs",
        "label": "Custos Logísticos",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "freight",
            "port_operations",
            "other_services",
            "logistics_labour",
        ],
    }),
    IndicatorStructure(**{
        "id": "freight",
        "label": "Freight",
        "type": "formula",
        "unit": "kUSD",
        "formulaId": "sum_children_formula",
        "children": [
            "sea_freight",
            "road_freight",
        ],
    }),
    IndicatorStructure(**{
        "id": "sea_freight",
        "label": "Sea Freight",
        "type": "input",
        "unit": "kUSD",
        "group": "Logística",
    }),
    IndicatorStructure(**{
        "id": "road_freight",
        "label": "Road Freight",
        "type": "input",
        "unit": "kUSD",
        "group": "Logística",
    }),
    IndicatorStructure(**{
        "id": "port_operations",
        "label": "Port Operations",
        "type": "input",
        "unit": "kUSD",
        "group": "Logística",
    }),
    IndicatorStructure(**{
        "id": "other_services",
        "label": "Other Services",
        "type": "input",
        "unit": "kUSD",
        "group": "Logística",
    }),
    IndicatorStructure(**{
        "id": "logistics_labour",
        "label": "Labour Logística",
        "type": "input",
        "unit": "kUSD",
        "group": "Logística",
    }),
]


def get_indicator_structures() -> list[IndicatorStructure]:
    return [indicator.model_copy(deep=True) for indicator in INDICATOR_STRUCTURES]
